name: Deploy static content to gh-pages branch

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write  # Necesario para escribir en gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install and build (opcional)
        run: echo "No build needed"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Usa './dist' o './public' si es tu caso
